runtime: python37

handlers:
- url: /static
  static_dir: static


env_variables:
  CLOUD_SQL_USERNAME: "root"
  CLOUD_SQL_PASSWORD: "123qweASD"
  CLOUD_SQL_DATABASE_NAME: "asintdb"
  CLOUD_SQL_CONNECTION_NAME: "asint-227116:europe-west2:asintserver"